name: Docker Image CI - sharelatex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          directory: server-ce
          file: server-ce/Dockerfile
          buildArgs: SHARELATEX_BASE_TAG=cdfmlr/sharelatex-base:main,MONOREPO_REVISION=$(shell git rev-parse HEAD)
          push: true
          tags: cdfmlr/sharelatex:${{github.ref_name}},cdfmlr/sharelatex:latest
